import pandas as pd
import numpy as np

"""
Topic Writing is the task of generating Reddit posts based on a summary while integrating the user's writing style.
Specifically, the temporal part refers to time-based setting. We evaluate whether the model successfully adapted user's writing style based on past posts.
"""

# Train
directory = "~/Desktop/LongLaMP/topic_writing_temporal/train/"
df_topic_writing_temporal_0 = pd.read_parquet(directory + "train-00000-of-00004.parquet")
df_topic_writing_temporal_1 = pd.read_parquet(directory + "train-00001-of-00004.parquet")
df_topic_writing_temporal_2 = pd.read_parquet(directory + "train-00002-of-00004.parquet")
df_topic_writing_temporal_3 = pd.read_parquet(directory + "train-00003-of-00004.parquet")

df_topic_writing_temporal_train = pd.concat([df_topic_writing_temporal_0, df_topic_writing_temporal_1, df_topic_writing_temporal_2, df_topic_writing_temporal_3])
print(df_topic_writing_temporal_train.head())
print(f"There are {len(df_topic_writing_temporal_train)} rows in topic writing temporal train dataset.")
print(df_topic_writing_temporal_train.columns)

# Val
directory = "~/Desktop/LongLaMP/topic_writing_temporal/val/"
df_topic_writing_temporal_val = pd.read_parquet(directory + "val-00000-of-00001.parquet")

print(df_topic_writing_temporal_val.head())
print(f"There are {len(df_topic_writing_temporal_val)} rows in topic writing temporal validation dataset.")
print(df_topic_writing_temporal_val.columns)

# Test
directory = "~/Desktop/LongLaMP/topic_writing_temporal/test/"
df_topic_writing_temporal_test = pd.read_parquet(directory + "test-00000-of-00001.parquet")

print(df_topic_writing_temporal_test.head())
print(f"There are {len(df_topic_writing_temporal_test)} rows in topic writing temporal testing dataset.")
print(df_topic_writing_temporal_test.columns)

"""
Topic Writing Temporal has 4 columns. They are author, output, input, and profile.
author: Author's username
output: The Reddit post content generated by the author
input: Prompt provided to the LLM, which includes short summary
profile: Profile of the author, which contains numerous sets of the author's username and the content written by the author
"""