import pandas as pd
import numpy as np

"""
Product Review is the task of generating product reviews based on product description, ratings, and a summary while integrating the user's writing style.
Specifically, the temporal part refers to time-based setting. We evaluate whether the model successfully adapted user's writing style based on past posts.
"""

# Train
directory = "~/Desktop/LongLaMP/product_review_temporal/train/"
df_product_reivew_0 = pd.read_parquet(directory + "train-00000-of-00003.parquet")
df_product_reivew_1 = pd.read_parquet(directory + "train-00001-of-00003.parquet")
df_product_reivew_2 = pd.read_parquet(directory + "train-00002-of-00003.parquet")

df_topic_product_reivew_temporal_train = pd.concat([df_product_reivew_0, df_product_reivew_1, df_product_reivew_2])
print(df_topic_product_reivew_temporal_train.head())
print(f"There are {len(df_topic_product_reivew_temporal_train)} rows in product review temporal train dataset.")
print(df_topic_product_reivew_temporal_train.columns)

# Val
directory = "~/Desktop/LongLaMP/product_review_temporal/val/"
df_topic_product_reivew_temporal_val = pd.read_parquet(directory + "val-00000-of-00001.parquet")

print(df_topic_product_reivew_temporal_val.head())
print(f"There are {len(df_topic_product_reivew_temporal_val)} rows in product review temporal validation dataset.")
print(df_topic_product_reivew_temporal_val.columns)

# Test
directory = "~/Desktop/LongLaMP/product_review_temporal/test/"
df_topic_product_reivew_temporal_test = pd.read_parquet(directory + "test-00000-of-00001.parquet")

print(df_topic_product_reivew_temporal_test.head())
print(f"There are {len(df_topic_product_reivew_temporal_test)} rows in product review temporal testing dataset.")
print(df_topic_product_reivew_temporal_test.columns)

"""
Product review temporal has 4 columns. They are reviewerId, input, output, and profile.
reviewerId: Unique identifier of the reviewer (author)
input: Prompt provided to the LLM. It contains product description, rating, and summary.
output: The long full text generated by the author, which expands upon the summary, contextualizes ratings, and provides commentary.
profile: Profile of the author, which contains numerous sets of description, rating, reviewText, and summary.
"""
